import './globals.css'
import UpperNav from './components/UpperNav';
import Header from './components/Header';
import Footer from './components/Footer';
import PopUp from './components/PopUp';
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossOrigin="anonymous" referrerPolicy="no-referrer" />
      </head>
      <body className={inter.className}>
        <UpperNav />
        <main className='pt-24 lg:pt-28'>
          <Header />
          {children}
          <Footer />
          <div className='bg-slate-800 text-white text-center py-3'>All rights reserved (2023) - BTG Immigration Consulting</div>
          <PopUp />
        </main>
      </body>
    </html>
  )
}
